### ISSUE TITLE
BUGFIX deal with files that report

### ISSUE THREAD

**Issue by iarigby** [freeuni-digital-technologies/homework-checker#33]
test/files-ში დაამატე ეს ქეისი

ახალი ტესტი შექმენი სადაც დატესტავ ამ ფაილს, ნახავ რა ხდება (დაწერე ქვემოთ) და მერე გამოასწორებ რომ დააბრუნოს ერორი "ფაილში იძახებ start() ფუნქციას. start() ფუნქცია მხოლოდ შექმენი, არსად გამოიძახო."

```js
function start(){
  move ():
  move ()
  move ();
  move () ;
  takeBall();
}

start();
```

**Comment by lnadi17** [comment]
როგორც მივხვდი ტესტ ფაილებს ცალკე ვქმნით და კარელის ფაილებს ცალკე, შემდეგ კი `karelTester.test.js`-დან `KarelTester` ობიექტს ვქმნით რომელსაც პირდაპირ `testSubmission` მეთოდი აქვს. როცა .k ფაილში აღწერილ ფუნქციას იმავე ფაილიდან ვიძახებთ, `setUpSubmission` მეთოდში 49-ე ხაზზე rewire-ს გამოძახება ფუჭდება. 

ჩვენს შემთხვევაში ასეთი ფაილის ტესტი არ წერია, თორემ getFileReaderError-ში გაფუჭდებოდა, რადგან რატომღაც error message არის "no beepers in this corner". ეს მესიჯი საიდან მოდის ჯერ ვერ გავარკვიე, პირდაპირ ამ ერორზე რომ შევამოწმო შეიძლება ყველა ქეისზე არ იმუშაოს... მეორე ვარიანტია პირდაპირ ფაილში შევამოწმო `start()` ხაზი თუ არსებობს, მაგრამ რამდენად გვაწყობს ეს არ ვიცი რადგან ცალკე გამოძახებული testSubmission ასეთ ფაილებზე არ იმუშავებს.

**Comment by lnadi17** [comment]
ვნახე და როცა rewire იძახება მაშინ ცდილობს მთლიანი კარელის ფუნქციის გამოძახებას და შიგნით გამოძახებისას თუ რამე არასწორად წავიდა ერორს აგდებს, რაც არასასურველი ქცევაა და ვერ ვივარაუდებთ რა მოხდება. შესაბამისად თუ ვინმე ფუნქციას იძახებს ფაილიდან setUpSubmission-მდე უნდა ვნახოთ და კონკრეტულად ამ ქეისისთვის დავაბრუნოთ მესიჯი.

**Comment by iarigby** [comment]
მოკლედ გადავხედე კიდევ ერთხელ და არ გეთანხმები რომ მოდულში უნდა იყოს შემოწმება. კარელის შემმოწმებელ პროგრამას უნდა შეეძლოს სტუდენტების მიერ ატვირთულ ნებისმიერ კოდის ფაილს გაუმკლავდეს. მაგალითად, თუ ფაილში start() ფუნქცია არ არის, შესაბამის ერორს აგდებს. არაა პრობლემა რომ rewire-ის გამოძახებამდე მოხდეს start() გამოძახების შემოწმება. მაგალითად, წინა ხაზში `replaceCustomStructures` ვიძახებთ რომ კოდის ფაილის პროცესინგი იყოს. ახლა აღარ გამოიყენება მაგრამ codehs-მდე მაგალითად, ჯავასკრიპტის ოდნავ სხვანაირ სინტაქსს იყენებდა სტენფორდის კარელი და ვცვლიდით იმას. ერორის ამოგდების მაგივრად, მაგ ფუნქციაში შეგიძლია replace ჩაამატო, `start();` ის ჩანაცვლება empty string-ით. და ახალ ფაილში (.fixed) შეინახო უსასრულო ლუპის გარეშე სტრინგი. ასე იმიტომ სჯობს, რომ უსასრულო ციკლის ახსნა სტუდენტებისთვის არ მგონია საჭირო, სჯობს უბრალოდ ჩვენით გავასწოროთ ეგ შეცდომა.

**Comment by lnadi17** [comment]
ანუ შეგვიძლია უბრალოდ ჩავასწოროთ ფაილი და ერორი არ დავაბრუნოთ? თუ კი ჩემთვის ჯობია ეგრე

**Comment by iarigby** [comment]
კი ეგ ვარიანტი სჯობს. უბრალოდ test case დაამატე ეგ უფრო მნიშვნელოვანია
(პრაქტიკის მხრივ)
